### ISSUE TITLE
Server-Side Pagination

### ISSUE THREAD

**Issue by Kenneth-Ngcobo** [Cheplusplus/ASE_2024_GROUP_C#103]
As a backend developer, I want to implement server-side pagination for search results, returning only a manageable set of results per page to improve performance and bandwidth efficiency.

**Comment by SABELOMAWELA** [comment]
Added server-side pagination to the recipe search API endpoint by introducing `page` and `limit` query parameters. This implementation uses skip and limit to control the number of search results returned per request, enhancing performance and bandwidth efficiency. Additionally, total recipe count and total pages are calculated and included in the response to facilitate smooth pagination handling on the frontend. This update ensures that users can navigate search results more effectively, even with our large db
